### ISSUE TITLE
Data isnt getting written to admin_data file. Returns empty value for API key and password 

### ISSUE THREAD

**Issue by koushik2296** [cyberark/conjur-quickstart#48] opened 2021-08-29 05:27 UTC
## Actual Results (including error logs, if applicable)
A clear and concise description of what actually did happen.

## Reproducible
   * [ ] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number
What version of the product are you running? Any version info that you can share is helpful. 
For example, you might give the version from Docker logs, the Docker tag, a specific download URL, 
the output of the `/info` route, etc.

## Environment setup
Can you describe the environment in which this product is running? Is it running on a VM / in a container / in a cloud? 
Which cloud provider? Which container orchestrator (including version)? 
The more info you can share about your runtime environment, the better we may be able to reproduce the issue.

**Comment by szh** [comment] 2023-02-06 18:59
I'm going to close this since there isn't any detail about how to reproduce. Please add details and reopen if this is still relevant.

**Closed by szh** 2023-02-06 18:59 UTC
Labels: component/conjur, kind/bug
