### ISSUE TITLE
Issue with OpenSSL, Postgres_databse and Conjur_server containers

### ISSUE THREAD

**Issue by amarrocco84** [cyberark/conjur-quickstart#11] opened 2020-02-17 17:44 UTC
Both the openssl container as well as the postgres containers exit. The conjur_server container restarts continually. I've been able to replicate this with three separate environments running Docker Toolbox and Docker CE.

![cyberarkoss](https://user-images.githubusercontent.com/60936141/74676093-35005000-5183-11ea-9ee8-5514e0fe72f1.JPG)

**Comment by uCatu** [comment] 2020-02-18 08:29
Hi @amarrocco84,

`openssl` container purpose is only to generate self-signed certificate and  should be in an exit state.

If `postgres` container is not up it will yield restarts in `conjur_server` container. 


Can you supply logs for postgres?
I suspect it might be EOL of postgres 9.4.

**Comment by sgnn7** [comment] 2020-02-18 15:10
Closing. Duplicate of #10

**Closed by sgnn7** 2020-02-18 15:10 UTC
