### ISSUE TITLE
Not able to Access Conjur REST APIs on gitbash and postman

### ISSUE THREAD

**Issue by ravics09** [cyberark/conjur-quickstart#40] opened 2021-02-09 14:21 UTC
Using conjur cli I able to use REST APIs to store and fetch secret (using host http://conjur). 
Like to set secret for username
`curl -H "$(conjur authn authenticate -H)" http://conjur/secrets/conjurAccount/variable/root%2Fdb%2Fusername  --data "ravics09"
`
But when I try same command in git bash I am getting error:
curl: (28) Failed to connect to 192.168.29.227 port 808: Timed out

Why Its trying to connect with given IP? Is any port mapping require ?
Or What setting require so I can test those REST APIs using postman?

My conjur server running on localhost port 8080.
![docker1](https://user-images.githubusercontent.com/4203655/107375082-5c77c780-6b0e-11eb-9a1a-92a141e5de5e.png)

**Comment by rpothier** [comment] 2021-02-09 16:05
Hi @ravics09 Can you share a little more setup information? What is the working configuration, is the working case on the same machine? Is postman being used in the working case? There shouldn't be a mapping, have you tried with setting the explicit port in the command?

**Comment by ravics09** [comment] 2021-02-10 03:04
Hi,
Setup Information:
Docker version - 2.5.0
OS - Windows 10 

Yes I am trying postman on same machine to test conjur REST APIs.  How I can set explicit port with the command.

**Comment by venkatesh22pv** [comment] 2021-02-10 10:50
I too trying same kind of scenario...trying to get secret from postman using restapi. Any solution found???

**Comment by rpothier** [comment] 2021-02-11 03:51
Hi @ravics09 In the git bash case shouldn't that be run inside the container?
i.e. docker-compose exec client curl ...

**Comment by ravics09** [comment] 2021-02-11 04:13
Hi  @rpothier ,
In case of postman, How we can access conjur rest apis,?
I searched regarding it but didn't find anything on internet.

**Comment by venkatesh22pv** [comment] 2021-02-11 07:35
guys is there any way to can access conjur rest apis in postman???

**Comment by rpothier** [comment] 2021-02-11 14:09
OK, thanks @ravics09 . So now it's ok with gitbash, and only an issue with Postman, is this correct?

**Comment by rpothier** [comment] 2021-02-11 16:29
Also, @ravics09 and @venkatesh22pv for questions on the API to use in postman, you can refer to https://github.com/cyberark/conjur-openapi-spec/wiki

**Comment by ravics09** [comment] 2021-02-12 03:17
Thanks @rpothier But I didn't find any good example on given link.

**Comment by rpothier** [comment] 2021-02-19 21:29
Hi @ravics09 How are you generating the token? Are you generating from the gitbash shell or the docker container.
you can generate the token by calling the docker container like this.
`curl -H  "$(docker-compose exec client conjur authn authenticate -H)" -k https://localhost:8443/whoami`

**Comment by john-odonnell** [comment] 2021-02-19 23:26
@ravics09 I've done a little digging into your issue. Found a couple different problems.

## Git-Bash
I think the problem you're experiencing is that the `"$(conjur authn authenticate -H)"` command substitution is occurring in your shell, and not in the `client` service, where the `conjur` executable resides.

This can be fixed by executing the command as a string, and escaping the contained `"` and `$`. This version of the command will substitute the authentication command from the shell of the `client` service, where it will execute successfully.
```
docker-compose exec client sh -c "curl -H \"\$(conjur authn authenticate -H)\" http://conjur/whoami"
```

## Postman
I would like to understand the problem you're having with Postman further, as I'm currently working on a guide for exploring the Conjur API using Postman and the [Conjur OpenAPI Spec](https://github.com/cyberark/conjur-openapi-spec). I have a preliminary version [here](https://github.com/cyberark/conjur-openapi-spec/tree/postman-guide#exploring-the-conjur-api-with-postman) if you want to take a look, any feedback is appreciated.

I think the problem is similar to the Git-Bash problem, where you are evoking `conjur` outside of the `conjur-cli`. In what context are you using the command `$(conjur authn authenticate -H)` in Postman? As a pre-request hook?

**Comment by ravics09** [comment] 2021-02-22 04:28
Hi @rpothier ,
I am trying to generate token in postman.
I tried 
`curl -H "$(docker-compose exec client conjur authn authenticate -H)" -k https://localhost:8443/whoami`

But its giving Authorization missing in response.

I don't want to generate access token in cli and use that in api call instead I want to generate access token with the api request in postman.

**Comment by rpothier** [comment] 2021-02-22 14:15
Hi @ravics09
For the issues with Postman, please refer to @john-odonnell [comments](https://github.com/cyberark/conjur-quickstart/issues/40#issuecomment-782450385) and the links he provided.

**Comment by rpothier** [comment] 2021-03-01 21:53
Hi @ravics09 Since the remaining questions are with Postman, can we close this issue?

**Closed** 2021-03-08 14:23 UTC
Labels: component/conjur, contributor, kind/bug
